mod.target=>26.1.2 <26.3

# https://fabricmc.net/develop
deps.minecraft=26.2-rc-1
deps.fabric_api=0.149.1+26.1.2

# https://modrinth.com/mod/modmenu/versions
runtime.modmenu=20.0.0-alpha.1
# https://modrinth.com/mod/rrv/versions
runtime.rrv=8.3.1+26.2-pre-5
runtime.jei=29.6.2.31
runtime.jei_mc=26.1.2